version: '3.8'

services:
  barnabe-backend:
    build: .
    container_name: barnabe_container
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEYS=${GEMINI_API_KEYS}
    restart: always